repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.1
    hooks:
      - id: poetry-sort
